import { getWeaponIcon } from "./getWeaponIcon"
export const WeaponsNav = [
    {
        title: "Great Sword",
        path: "/weapons/gs",
        id: 0,
        icon: getWeaponIcon("gs"),
        cName: "nav-text",
    },
    {
        title: "Sword and Shield",
        path: "/weapons/sns",
        id: 1,
        icon: getWeaponIcon("sns"),
        cName: "nav-text",
    },
    {
        title: "Dual Blades",
        path: "/weapons/dbs",
        id: 2,
        icon: getWeaponIcon("dbs"),
        cName: "nav-text",
    },
    {
        title: "Longsword",
        path: "/weapons/ls",
        id: 3,
        icon: getWeaponIcon("ls"),
        cName: "nav-text",
    },
    {
        title: "Hammer",
        path: "/weapons/hammer",
        id: 4,
        icon: getWeaponIcon("ham"),
        cName: "nav-text",
    },
    {
        title: "Hunting Horn",
        path: "/weapons/hunting-horn",
        id: 5,
        icon: getWeaponIcon("hh"),
        cName: "nav-text",
    },
    {
        title: "Lance",
        path: "/weapons/lance",
        id: 6,
        icon: getWeaponIcon("lance"),
        cName: "nav-text",
    },
    {
        title: "Gunlance",
        path: "/weapons/gunlance",
        id: 7,
        icon: getWeaponIcon("gl"),
        cName: "nav-text",
    },
    {
        title: "Switch Axe",
        path: "/weapons/switch-axe",
        id: 8,
        icon: getWeaponIcon("sa"),
        cName: "nav-text",
    },
    {
        title: "Charge Blade",
        path: "/weapons/charge-blade",
        id: 9,
        icon: getWeaponIcon("lance"),
        cName: "nav-text",
    },
    {
        title: "Insect Glaive",
        path: "/weapons/insect-glaive",
        id: 10,
        icon: getWeaponIcon("ig"),
        cName: "nav-text",
    },
    {
        title: "Bow",
        path: "/weapons/bow",
        id: 11,
        icon: getWeaponIcon("bow"),
        cName: "nav-text",
    },
    {
        title: "Light Bowgun",
        path: "/weapons/light-bowgun",
        id: 12,
        icon: getWeaponIcon("lbg"),
        cName: "nav-text",
    },
    {
        title: "Heavy Bowgun",
        path: "/weapons/heavy-bowgun",
        id: 13,
        icon: getWeaponIcon("hbg"),
        cName: "nav-text",
    },

]